### ISSUE TITLE
"integration has been configured" posts to the channel, but no updates

### ISSUE THREAD

**Issue by brandoncurtis** [optionfactory/gdrive2slack#11]
I've had it happen several times now where I've registered a configuration, the registration is confirmed on the hosted site and a confirmation posts to Slack, but Google Drive activities fail to post.  Once this happens to an account, something is 'stuck' and submitting another configuration doesn't help.  Removing the integration and waiting a day doesn't help either.

**Comment by xicubed** [comment]
I'm not seeing updates either. I get the bot message within slack:

Google DriveBOT [1:21 PM] 
A GDrive2Slack integration has been configured by @blblabla Activities on Google Drive documents will be notified here.

And a success message on the website but nothing else ever shows up in slack no matter what changes I make within the watched drive folder.

**Comment by EdMcBane** [comment]
Looking into it, might take a little while though.
Can you please send us the gmail account you used to register to gdrive2slack@optionfactory.net , so we can look into your issue specifically?

**Comment by xicubed** [comment]
The email I used was michaellopez@boisestate.edu.

Thanks,

mal

**Comment by n2ygk** [comment]
Happening for me too. Another google apps for edu customer (ac45@columbia.edu). I know our admin console blocks non-core apps, so maybe this is related? All the oauth stuff seemed to happen properly though.

**Comment by Marviel** [comment]
Same issue here.

**Comment by mdominoni** [comment]
I managed to install from source code (github) in one of our servers, everything was ok in the subscription, but we dont recieve any new notifications from Google Drive to Slack.

I have enabled to following APIs from Google: Drive, Picker, Contacts, Google+
And created the following Credentials: OAuth 2.0 Clients Id, API key

I also try to use your hosted service, same problem.
Any thoughts or comments?

Thank you!

**Comment by jwSPIX** [comment]
Any resolutions on this? I've been trying to get up this integrations for a few days now with this same issue.

![image](https://cloud.githubusercontent.com/assets/17075824/12835337/6af69872-cc03-11e5-93a8-d15261266d3b.png)

Initial post above, then nothing.

**Comment by Marviel** [comment]
@jwSPIX I had some permissions issues with the folders in google drive that, when resolved (for other reasons) seemed to clear up the problem. Make sure you have explicit Read permissions on all the files you are wishing to track changes on, would be a good place to start.

**Comment by Marviel** [comment]
Not that that will certainly solve the problem...

**Comment by teddyboar** [comment]
We have rolled up an update in production fixing a problem with users having a large number of folders in their google drive account; this should be fixed, please open another ticket if the problem persists.

@Marviel Thanks for helping!
