### ISSUE TITLE
Updates stop and only restart by re-registering the integration

### ISSUE THREAD

**Issue by brandoncurtis** [optionfactory/gdrive2slack#13]
I registered the gdrive2slack integration with uc.cheme.gsac@gmail.com on 2015-09-22 and gDrive updates were posted successfully to my Slack channel.  They stopped posting on 2015-10-07, though no configurations were changed.

I re-registered the integration today (2015-10-14) and it appears to be working again.

**Comment by teddyboar** [comment]
This has been adressed in the past by changing how we handle google failures,
Closing the ticket as it should now be fixed, let us know if the problem persists.
