### ISSUE TITLE
Slack permissions are too broad

### ISSUE THREAD

**Issue by McKayDavis** [optionfactory/gdrive2slack#14]
When setting up the integration, during step 2 (authorizing gdrive2slack to access my Slack account), I see the following warning about permissions from Slack:

**Access all content in <slack instance name>**
**gdrive2slack will be able to read all messages, files, and profiles that you can access.**

So, I backed out.  I'm sure others do to as they don't want optionfactory (or some other third party that may host gdrive2slack) to have access to all of thier slack messages.

BTW, the main site (gdrive2slack.optionfactory.net) indicates otherwise:
*Which permissions do you require?
We ask for the bare minimum permissions required to offer our service.
On Slack:
* post to be able to send new messages to your slack domain

I haven't looked at the code, but I assume the integration doesn't actually need full access to Slack content.

**Comment by rferranti** [comment]
Hello McKayDavis,
source code you should be looking for is [here](https://github.com/optionfactory/gdrive2slack/blob/49e814e2be42f1bcd3761de02fafd5fc5ef526bd/templates/index.tmpl#L337-L343): you can see we are asking for identify and write scopes, which were, at the time gdrive2slack was written, the bare minimum needed for the service to work.

[Slack API documentation](https://api.slack.com/docs/oauth-scopes) currently lists new scopes which could help narrowing access rights to slack. I'll do some testing and create a patch changing requested scopes (probably identify,channels:read,chat:write:bot) as soon as i can.


Thanks for you time

**Comment by rferranti** [comment]
now using `identify,chat:write:bot`. production server is up-to-date
