### ISSUE TITLE
Allow Notifications to be configurable

### ISSUE THREAD

**Issue by MikeSchroll** [optionfactory/gdrive2slack#8]
The default is to say (configured @user)

Unfortunately this means whichever user configures things, EVERY single update also notifies that user.... since the default is for @user to be a notification trigger.

It'd be great to either change this default, or have an ability to modify that line of the notifications, so I can remove my own @mikeschroll from the list.

Slack is not very fun when I personally get @mentioned every single time anyone tweaks a file!

**Comment by teddyboar** [comment]
Hello Mike,
you are right, this could be very annoying, so I just removed "(configured by @user)" and rolled out the update to prod. This patch leaves out a few problems such as identifying a trigger, but we can work on that later.
Hope this helps, thanks for your feedback.

**Comment by MikeSchroll** [comment]
Thank you SOO much!

**Comment by teddyboar** [comment]
A small update on this matter:
* `<@user|USERID>` triggers a slack notification
* both `@user` and `user` trigger an highlight, and consequently a slack notification (by default)

so it seems to be impossible to mention a user without triggering a notification.

I hacked a solution in 22247f4e361f2c264b5ec7209293c6c5333b45c8 by adding a zero width space `\u200b` after the first codepoint when mentioning a user and it seems to prevent the unwanted notification.

**Comment by MikeSchroll** [comment]
Agreed -- this has been working well, that it shows the relevant info, without triggering the notifications.
