### ISSUE TITLE
Ignore MS Office Temp Files

### ISSUE THREAD

**Issue by gavinhodge** [optionfactory/gdrive2slack#9]
We use Google Drive mostly for file synchronisation, and mostly edit files using MS Office products on Windows. When opening a file, office creates a temporary file which is sync'd by Drive and causes a Slack notification. There's a similar notification when the file is closed and Office deletes the temp file.

It would be great to filter out these files from generating notifications, or have a way to configure patters that should be ignored.

The files in question would match the following regex: ^~\$.*

**Comment by teddyboar** [comment]
I'm creating a patch with the suggested filter enabled by default, we can add a configuration option to disable it later (if needed)

thanks for the feedback

**Comment by teddyboar** [comment]
89a97dedb730b3fe8d8f847ad40c4f8f93089284 updated live server a few minutes ago

**Comment by gavinhodge** [comment]
Wow, that was amazingly quick. You guys are awesome!
